[package]
name = "dyll"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = "0.10.4"
regex = "1.10"
clap = { version = "4.5", features = ["derive"] }
bindgen = "0.69"
syn = "2.0"
quote = "1.0"

[dev-dependencies]
tempfile = "3.0"
